### ISSUE TITLE
Some tests fail in Chrome

### ISSUE THREAD

**Issue by TehShrike** [Raynos/xhr#113]
Chrome 49, OSX.

I noticed it while opening #112.

I had to change the testing a bit in that one, so I haven't drilled down into this very much.  Whenever that other pull request gets dealt with I should be able to dig in further.

```
TAP version 13
# constructs and calls callback without throwing
ok 1 got here
# [func] Can GET a url (cross-domain)
ok 2 no err
ok 3 should be equal
ok 4 should be equal
ok 5 should not be equal
ok 6 should be equal
ok 7 should not be equal
# [func] Returns http error responses like npm's request (cross-domain)
ok 8 no err
ok 9 should be equal
ok 10 should be equal
# [func] Times out to an error 
ok 11 should return error
ok 12 should be equal
ok 13 should be equal
ok 14 should be equal
# withCredentials option
ok 15 withCredentials not true
ok 16 withCredentials set to true
# withCredentials ignored when using synchronous requests
ok 17 sync overrides withCredentials
# XDR usage (run on IE8 or 9)
ok 18 Uses XDR when told to
# handles errorFunc call with no arguments provided
ok 19 callback should get an error
ok 20 error message incorrect
ok 21 should not throw when error handler called without arguments
# constructs and calls callback without throwing
ok 22 callback is not optional
# [func] xhr[method] get, put, post, patch
not ok 23 no err
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [Error: Internal XMLHttpRequest Error]
    at: Test.assert [as _assert] (http://localhost:3000/tests-bundle.js:6711:17)
    stack: |-
      Error: Internal XMLHttpRequest Error
          at loadFunc (http://localhost:3000/tests-bundle.js:132:19)
          at XMLHttpRequest.readystatechange (http://localhost:3000/tests-bundle.js:64:13)
  ...
not ok 24 should be equal
  ---
    operator: equal
    expected: 200
    actual:   0
    at: Test.assert [as _assert] (http://localhost:3000/tests-bundle.js:6711:17)
  ...
not ok 25 should be equal
  ---
    operator: equal
    expected: 'PUT'
    actual:   undefined
    at: Test.assert [as _assert] (http://localhost:3000/tests-bundle.js:6711:17)
  ...
Uncaught TypeError: Cannot read property 'length' of undefined
http://localhost:3000/tests-bundle.js:10263
not ok 26 no err
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [Error: Internal XMLHttpRequest Error]
    at: Test.assert [as _assert] (http://localhost:3000/tests-bundle.js:6711:17)
    stack: |-
      Error: Internal XMLHttpRequest Error
          at loadFunc (http://localhost:3000/tests-bundle.js:132:19)
          at XMLHttpRequest.readystatechange (http://localhost:3000/tests-bundle.js:64:13)
  ...
not ok 27 should be equal
  ---
    operator: equal
    expected: 200
    actual:   0
    at: Test.assert [as _assert] (http://localhost:3000/tests-bundle.js:6711:17)
  ...
not ok 28 should be equal
  ---
    operator: equal
    expected: 'PATCH'
    actual:   undefined
    at: Test.assert [as _assert] (http://localhost:3000/tests-bundle.js:6711:17)
  ...
Uncaught TypeError: Cannot read property 'length' of undefined
http://localhost:3000/tests-bundle.js:10263
ok 29 no err
ok 30 should be equal
ok 31 should be equal
ok 32 should not be equal
ok 33 no err
ok 34 should be equal
ok 35 should be equal
ok 36 should not be equal
# xhr[method] get, put, post, patch with url shorthands
ok 37 should be equal
ok 38 should be equal
ok 39 should be equal
ok 40 should be equal
# xhr[method] get, put, post, patch with url shorthands and options
ok 41 should be equal
ok 42 should be equal
ok 43 should be equal
ok 44 should be equal
ok 45 should be equal
ok 46 should be equal
ok 47 should be equal
ok 48 should be equal
# [func] xhr.head
not ok 49 no err
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [Error: Internal XMLHttpRequest Error]
    at: Test.assert [as _assert] (http://localhost:3000/tests-bundle.js:6711:17)
    stack: |-
      Error: Internal XMLHttpRequest Error
          at loadFunc (http://localhost:3000/tests-bundle.js:132:19)
          at XMLHttpRequest.readystatechange (http://localhost:3000/tests-bundle.js:64:13)
  ...
not ok 50 should be equal
  ---
    operator: equal
    expected: 200
    actual:   0
    at: Test.assert [as _assert] (http://localhost:3000/tests-bundle.js:6711:17)
  ...
not ok 51 should be equal
  ---
    operator: equal
    expected: 'HEAD'
    actual:   undefined
    at: Test.assert [as _assert] (http://localhost:3000/tests-bundle.js:6711:17)
  ...
ok 52 (unnamed assert)
# xhr.head url shorthand
ok 53 should be equal
# [func] xhr.del
ok 54 no err
ok 55 should be equal
ok 56 should be equal
ok 57 should not be equal
# xhr.del url shorthand
ok 58 should be equal
# url signature without object
ok 59 should be equal
# url signature with object
ok 60 should be equal
ok 61 should be equal
# XHR can be overridden
ok 62 created the custom XHR
ok 63 created the custom XDR

1..63
# tests 63
# pass  54
# fail  9

Results sent!
```

**Comment by TehShrike** [comment]
It looks like #106 is actually an attempt at a solution to this issue.

**Comment by naugtur** [comment]
I expect this to be related to some of the urls being on the web. 
After merging the mock server, we can transfer everything to localhost.

**Comment by naugtur** [comment]
Works for me on current master. Could you please retry?

**Comment by TehShrike** [comment]
I tested in Chrome 49 and Chrome 51.  In both cases, the tests passed in incognito mode, but failed in the regular browsing mode.  So weird!

**Comment by naugtur** [comment]
Any ad/script blockers installed? Any cross-origin related messages in console?
I just tested on chrome 53 and chromium 50, passed both.

**Comment by TehShrike** [comment]
I do have ad blockers installed on the Chrome 51 I tested on just now, though they all claimed to not be doing anything when I browsed to localhost.

I got the tests to fail once for me in Chrome 49 testing with Browserstack.  I've tested on more versions of Chrome just now on various operating systems using Browserstack, and haven't seen any more failures.

The first error in the console (and a bunch after) is a 404 response to `http://localhost:3000/undefined`.

**Comment by naugtur** [comment]
try current master, I switched most tests to use localhost and fixed a thing btw.

**Comment by TehShrike** [comment]
I pulled down current master and ran the tests several times on a few different versions of Chrome, and couldn't reproduce. Wheeeeeee!

It's probably good now.

**Comment by naugtur** [comment]
I tested in multiple browsers on Linux and Windows. (IE9 IE11 old safaris and firefoxes)
I'm releasing now.
